version: "3.3"

services:

  urlshortener:
    build: ./app/.
    container_name: "url-shortener"
    restart: "always"
    networks:
      - web
    working_dir: /app
    command: python3 -m gunicorn -w 4 application:app -b 0.0.0.0:8000

  nginx:
    build: ./nginx/.
    container_name: "nginx"
    restart: "always"
    ports:
      - "80:80"
    networks:
      - web
    depends_on:
      - urlshortener

  cypress:
    build: ./cypress/.
    container_name: "cypress"
    restart: "no"
    volumes:
      - "./cypress/test-reports:/test-reports"
    networks:
      - web
    depends_on:
      - nginx
    working_dir: /
    command: cypress run --config video=false --spec /cypress/integration/test.spec.js

networks:
  web: