version: "3.3"

services:

  urlshortener:
    build: ./app/.
    container_name: "url-shortener"
    restart: "always"
    ports:
      - "8000:8000"
    network_mode: bridge
    command: python3 -m gunicorn -w 4 application:app -b 0.0.0.0:8000