version: "3.3"

services:

  urlshortener:
    build: ./app/.
    container_name: "url-shortener"
    restart: "always"
    ports:
      - "8000:8000"
    networks:
      - web
    working_dir: /app
    command: python3 -m gunicorn -w 4 application:app -b 0.0.0.0:8000

  nginx:
    build: ./nginx/.
    container_name: "nginx"
    restart: "always"
    ports:
      - "5000:80"
    networks:
      - web

networks:
  web: